name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build & Install
      working-directory: e2e
      run: dotnet build
    - name: Ensure browsers are installed
      working-directory: e2e
      run: pwsh CarvedRock.End2End.Tests/bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Run your tests
      working-directory: e2e
      run: dotnet test -s ./aca-firefox.runsettings