name: Playwright Tests
on:
  workflow_dispatch:
  
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.51.0-noble # :latest? or remove tag
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build
        run: dotnet build
        working-directory: e2e
      - name: Run your tests
        run: dotnet test
        working-directory: e2e